### ISSUE TITLE
extern macro error

### ISSUE THREAD

**Issue by nidud** [Baron-von-Riedesel/JWasm#1] opened 2018-08-20 11:12 UTC
Hi japheth. I'll add some of the issues fixed in Asmc here.

macro28.asm:
```
include macro.inc

    end
```

macro.inc:
```
    .386
    .model flat
    .code


line_error macro line

    mov ax,line1
    exitm<eax>
    endm

    mov edx,line_error(5)
```
macro28.asm(12) : Error A2102: Symbol not defined : line1

**Comment by Baron-von-Riedesel** [comment] 2020-02-16 13:25
Ok, if I understand correctly, the problem is that the wrong source file is displayed in the error msg.
Will be fixed in v2.13pre6.

**Closed by Baron-von-Riedesel** 2020-02-16 13:25 UTC
